spring.application.name=api-gateway

server.port=9095

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.routes[0].uri=http://localhost:6001
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=USER-SERVICE
spring.cloud.gateway.routes[1].uri=http://localhost:6002
spring.cloud.gateway.routes[1].predicates[0]=Path=/citizens/**

spring.cloud.gateway.routes[2].id=OFFICER-SERVICE
spring.cloud.gateway.routes[2].uri=http://localhost:6002
spring.cloud.gateway.routes[2].predicates[0]=Path=/officers/**

spring.cloud.gateway.routes[3].id=REQUEST-SERVICE
spring.cloud.gateway.routes[3].uri=http://localhost:6003
spring.cloud.gateway.routes[3].predicates[0]=Path=/requests/**

spring.cloud.gateway.routes[4].id=DASHBOARD-SERVICE
spring.cloud.gateway.routes[4].uri=http://localhost:6003
spring.cloud.gateway.routes[4].predicates[0]=Path=/dashboard/**

spring.cloud.gateway.routes[5].id=INTEGRATION-SERVICE
spring.cloud.gateway.routes[5].uri=http://localhost:6003
spring.cloud.gateway.routes[5].predicates[0]=Path=/integration/**

logging.level.org.springframework.cloud.gateway=DEBUG
